Aditya 25 nwsensor
mlab-upenn/cea-os pull request #43
Opened 2021-07-04 00:18 UTC by adityaguptakd

2021-07-08 15:28 UTC, nandantumu requested changes

2021-07-08 15:28 UTC, nandantumu commented on ceaos/actuators/actuator_definition.py
> +        pass
Newline

2021-07-08 15:28 UTC, nandantumu commented on ceaos/actuators/sample_actuator.py
> +        self.datatype = datatype
Newline

2021-07-08 15:28 UTC, nandantumu commented on ceaos/actuators/sample_actuator.py
> +class Artificial_Actuator(Actuator):
Can you change the class name to `ArtificialActuator`?

2021-07-08 15:28 UTC, nandantumu commented on docker-compose.yml
> +            - 23267
You should only need one of these

2021-07-08 15:28 UTC, nandantumu commented on ceaos/sensors/sensor_definition.py
> -        pass
Why did you delete this?

2021-07-08 15:28 UTC, nandantumu commented on scripts/runner.py
> +    print("Threads: ", len(threads))
Can you change this print statement to a logging statement? Perhaps merge with the statement below

2021-07-08 16:06 UTC, adityaguptakd commented
Also Nandan, in the main branch we no longer need stuff like temp_sens.py that was originally comitted because we didn't have the network sensor idea at the time, but now that stuff is completely useless. Not sure if there is a way for you to decommit it

2021-07-09 16:52 UTC, nandantumu commented
Yup, we can just make a refactoring commit that deletes those.

2021-07-09 16:55 UTC, nandantumu approved these changes
LGTM!

2021-07-13 15:55 UTC, merged